services:
  web:
    build: .
    container_name: uaiss_web_app
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./exams.db:/app/exams.db
      - ./config.json:/app/config.json
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - SYS_TIME
    restart: unless-stopped
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
