services:
  web:
    build: .
    container_name: uaiss_web_app
    ports:
      - "8000:8000"
    volumes:
      - ./exams.db:/app/exams.db
      - ./config.json:/app/config.json
    restart: unless-stopped
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"